In [104]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [105]:
df=pd.read_csv("/content/train.csv")
df.head(2)

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
0,0,66,92887,23.4,2,3,7,1,Male,Suburban,Sedan,Yes,No,Low,No
1,1,38,30000,5.0,1,2,2,4,Male,Rural,SUV,Yes,No,Low,No

In [106]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 668665 entries, 0 to 668664
Data columns (total 15 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id                           668665 non-null  int64
 1   Age                          668665 non-null  int64
 2   Annual_Income_USD            668665 non-null  int64
 3   Daily_Commute_km             668665 non-null  float64
 4   Number_of_Cars_Owned         668665 non-null  int64
 5   Charging_Stations_Near_Home  668665 non-null  int64
 6   Charging_Stations_Near_Work  668665 non-null  int64
 7   Environmental_Concern_Level  668665 non-null  int64
 8   Gender                       668665 non-null  object
 9   City_Type                    668665 non-null  object
 10  Current_Car_Type             668665 non-null  object
 11  Home_Charging_Possible       668665 non-null  object
 12  Subsidy_Available            668665 non-null  object
 13  Range_Anxiety_Level          668665 non-null  object
 14  Will_Buy_EV                  668665 non-null  object
dtypes: float64(1), int64(7), object(7)
memory usage: 76.5+ MB

In [107]:
df.describe()

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level
count,668665.00000,668665.000000,668665.000000,668665.000000,668665.000000,668665.000000,668665.000000,668665.000000
mean,334332.00000,47.039171,84769.266989,32.158298,1.712626,4.960408,7.176314,2.935477
std,193027.10321,12.875448,28648.029042,18.730474,0.729275,3.926843,5.186627,1.429119
min,0.00000,25.000000,30000.000000,5.000000,1.000000,0.000000,0.000000,1.000000
25%,167166.00000,36.000000,67376.000000,17.200000,1.000000,2.000000,3.000000,2.000000
50%,334332.00000,47.000000,84880.000000,33.600000,2.000000,4.000000,6.000000,3.000000
75%,501498.00000,58.000000,102753.000000,47.400000,2.000000,7.000000,10.000000,4.000000
max,668664.00000,69.000000,188549.000000,98.700000,4.000000,14.000000,19.000000,5.000000

In [108]:
df.isnull().sum()  #checking null values.no null values in the data so, the data is clean

id                             0
Age                            0
Annual_Income_USD              0
Daily_Commute_km               0
Number_of_Cars_Owned           0
Charging_Stations_Near_Home    0
Charging_Stations_Near_Work    0
Environmental_Concern_Level    0
Gender                         0
City_Type                      0
Current_Car_Type               0
Home_Charging_Possible         0
Subsidy_Available              0
Range_Anxiety_Level            0
Will_Buy_EV                    0
dtype: int64

In [109]:
df.duplicated().sum()#checking duplicates no duplicates

np.int64(0)

In [110]:
df.describe(exclude=np.number)

,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
count,668665,668665,668665,668665,668665,668665,668665
unique,3,3,4,2,2,3,2
top,Male,Urban,Sedan,Yes,Yes,Low,No
freq,367954,289305,303459,462677,419909,603972,551886

In [111]:
df['Will_Buy_EV'].value_counts(normalize=True)

Will_Buy_EV
No     0.825355
Yes    0.174645
Name: proportion, dtype: float64

In [112]:
x=df.drop(columns=['Will_Buy_EV'])
y=df['Will_Buy_EV']

In [113]:
x.head(1)

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level
0,0,66,92887,23.4,2,3,7,1,Male,Suburban,Sedan,Yes,No,Low

In [114]:
x['Daily_Commute_km']=x['Daily_Commute_km'].fillna(x['Daily_Commute_km'].median())
x['Number_of_Cars_Owned']=x['Number_of_Cars_Owned'].fillna(x['Number_of_Cars_Owned'].median())

x['Charging_Stations_Near_Home']=x['Charging_Stations_Near_Home'].fillna(x['Charging_Stations_Near_Home'].median())

x['Charging_Stations_Near_Work']=x['Charging_Stations_Near_Work'].fillna(x['Charging_Stations_Near_Work'].median())

In [115]:
x.isnull().sum()

id                             0
Age                            0
Annual_Income_USD              0
Daily_Commute_km               0
Number_of_Cars_Owned           0
Charging_Stations_Near_Home    0
Charging_Stations_Near_Work    0
Environmental_Concern_Level    0
Gender                         0
City_Type                      0
Current_Car_Type               0
Home_Charging_Possible         0
Subsidy_Available              0
Range_Anxiety_Level            0
dtype: int64

In [116]:
x['Environmental_Concern_Level']=x['Environmental_Concern_Level'].fillna(x['Environmental_Concern_Level'].median())
x['Range_Anxiety_Level']=x['Range_Anxiety_Level'].fillna(x['Range_Anxiety_Level'].mode()[0])
x['Gender']=x['Gender'].fillna(x['Gender'].mode()[0])
x['City_Type']=x['City_Type'].fillna(x['City_Type'].mode()[0])
x['Current_Car_Type']=x['Current_Car_Type'].fillna(x['Current_Car_Type'].mode()[0])
x['Home_Charging_Possible']=x['Home_Charging_Possible'].fillna(x['Home_Charging_Possible'].mode()[0])
x['Subsidy_Available']=x['Subsidy_Available'].fillna(x['Subsidy_Available'].mode()[0])

In [117]:
x.isnull().sum()

id                             0
Age                            0
Annual_Income_USD              0
Daily_Commute_km               0
Number_of_Cars_Owned           0
Charging_Stations_Near_Home    0
Charging_Stations_Near_Work    0
Environmental_Concern_Level    0
Gender                         0
City_Type                      0
Current_Car_Type               0
Home_Charging_Possible         0
Subsidy_Available              0
Range_Anxiety_Level            0
dtype: int64

In [118]:
y.head(1)

0    No
Name: Will_Buy_EV, dtype: object

In [119]:
y = y.fillna(y.mode()[0])

In [120]:
#encoding categorical variables

cat_columns=x.select_dtypes(exclude=np.number)
cat_columns.head(2)

,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level
0,Male,Suburban,Sedan,Yes,No,Low
1,Male,Rural,SUV,Yes,No,Low

In [121]:
num_data=x.select_dtypes(include=np.number)
num_data.head(2)

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level
0,0,66,92887,23.4,2,3,7,1
1,1,38,30000,5.0,1,2,2,4

In [122]:
#lets check their unique values. Because type of encoding depends on no of categories
for col in cat_columns:
  print('\n',col)
  print(cat_columns[col].value_counts())

 Gender
Gender
Male      367954
Female    295427
Other       5284
Name: count, dtype: int64

 City_Type
City_Type
Urban       289305
Suburban    255377
Rural       123983
Name: count, dtype: int64

 Current_Car_Type
Current_Car_Type
Sedan        303459
SUV          246545
Hatchback     79438
Truck         39223
Name: count, dtype: int64

 Home_Charging_Possible
Home_Charging_Possible
Yes    462677
No     205988
Name: count, dtype: int64

 Subsidy_Available
Subsidy_Available
Yes    419909
No     248756
Name: count, dtype: int64

 Range_Anxiety_Level
Range_Anxiety_Level
Low       603972
Medium     62499
High        2194
Name: count, dtype: int64

In [123]:
y = y.map({'Yes':1,'No':0})

In [124]:
encoded_data=pd.get_dummies(cat_columns[['Gender','City_Type','Current_Car_Type']],drop_first=True,dtype=int)

In [125]:
cat_columns[['Range_Anxiety_Level']].isnull().sum()

Range_Anxiety_Level    0
dtype: int64

In [126]:
from sklearn.preprocessing import OrdinalEncoder
categories=['Low','Medium','High']
OE=OrdinalEncoder(categories=[categories])
cat_columns['Range_Anxiety_Level']=OE.fit_transform(cat_columns[['Range_Anxiety_Level']])

In [127]:
cat_columns['Home_Charging_Possible']=cat_columns['Home_Charging_Possible'].map({'Yes':1,'No':0})
cat_columns['Subsidy_Available']=cat_columns['Subsidy_Available'].map({'Yes':1,'No':0})

In [128]:
final_encoded_data=pd.concat([cat_columns,encoded_data],axis=1)

In [129]:
final_encoded_data.head(2)

,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Gender_Male,Gender_Other,City_Type_Suburban,City_Type_Urban,Current_Car_Type_SUV,Current_Car_Type_Sedan,Current_Car_Type_Truck
0,Male,Suburban,Sedan,1,0,0.0,1,0,1,0,0,1,0
1,Male,Rural,SUV,1,0,0.0,1,0,0,0,1,0,0

In [130]:

final_encoded_data.drop(columns=['Gender','City_Type','Current_Car_Type'],inplace=True)

In [131]:
final_encoded_data.head(1)

,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Gender_Male,Gender_Other,City_Type_Suburban,City_Type_Urban,Current_Car_Type_SUV,Current_Car_Type_Sedan,Current_Car_Type_Truck
0,1,0,0.0,1,0,1,0,0,1,0

In [132]:
#now need to combine a numerical variables and encoded_variables
final_df=pd.concat([final_encoded_data,num_data],axis=1)

In [133]:
final_df.head(2)

,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Gender_Male,Gender_Other,City_Type_Suburban,City_Type_Urban,Current_Car_Type_SUV,Current_Car_Type_Sedan,Current_Car_Type_Truck,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level
0,1,0,0.0,1,0,1,0,0,1,0,0,66,92887,23.4,2,3,7,1
1,1,0,0.0,1,0,0,0,1,0,0,1,38,30000,5.0,1,2,2,4

In [134]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(final_df,y,train_size=0.8,random_state=100)

In [135]:
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

(534932, 18)
(133733, 18)
(534932,)
(133733,)

In [136]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain[['Age','Annual_Income_USD','Daily_Commute_km']]=sc.fit_transform(xtrain[['Age','Annual_Income_USD','Daily_Commute_km']])
xtest[['Age','Annual_Income_USD','Daily_Commute_km']]=sc.transform(xtest[['Age','Annual_Income_USD','Daily_Commute_km']])

In [137]:
xtrain.head(2)

,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Gender_Male,Gender_Other,City_Type_Suburban,City_Type_Urban,Current_Car_Type_SUV,Current_Car_Type_Sedan,Current_Car_Type_Truck,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level
463046,1,1,0.0,0,0,0,1,0,1,0,463046,0.928838,-0.036775,-1.450173,2,7,17,4
555627,1,0,0.0,0,0,1,0,0,0,0,555627,-1.090300,0.310177,0.606091,2,1,4,2

In [138]:

xtrain.drop(columns=['id'],inplace=True)
xtest.drop(columns=['id'],inplace=True)

In [139]:
xtrain.head(2)

,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Gender_Male,Gender_Other,City_Type_Suburban,City_Type_Urban,Current_Car_Type_SUV,Current_Car_Type_Sedan,Current_Car_Type_Truck,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level
463046,1,1,0.0,0,0,0,1,0,1,0,0.928838,-0.036775,-1.450173,2,7,17,4
555627,1,0,0.0,0,0,1,0,0,0,0,-1.090300,0.310177,0.606091,2,1,4,2

In [140]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
lr=LogisticRegression(max_iter=1000)
lr.fit(xtrain,ytrain)
ypred=lr.predict(xtest)

In [141]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.93      0.95      0.94    110364
           1       0.72      0.66      0.69     23369

    accuracy                           0.90    133733
   macro avg       0.82      0.80      0.81    133733
weighted avg       0.89      0.90      0.89    133733

In [142]:
y.head(2)

0    0
1    0
Name: Will_Buy_EV, dtype: int64

In [143]:
y_prob=lr.predict_proba(xtest)[:,1]

In [144]:
from sklearn.metrics import roc_auc_score
roc_auc_score(ytest,y_prob)

np.float64(0.9378955547311943)

In [145]:
test_df=pd.read_csv("/content/test.csv")
test_df.head(2)

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level
0,668665,61,67725.0,16.9,2,7,4,4.0,Male,Suburban,Sedan,Yes,No,Low
1,668666,42,152835.0,41.9,2,9,9,4.0,Male,Urban,SUV,No,No,Low

In [146]:
test_df.isnull().sum()

id                             0
Age                            0
Annual_Income_USD              0
Daily_Commute_km               0
Number_of_Cars_Owned           0
Charging_Stations_Near_Home    0
Charging_Stations_Near_Work    0
Environmental_Concern_Level    0
Gender                         0
City_Type                      0
Current_Car_Type               0
Home_Charging_Possible         0
Subsidy_Available              0
Range_Anxiety_Level            0
dtype: int64

In [147]:
test_df.duplicated().sum()

np.int64(0)

In [148]:
test_df.drop(columns=['id'],inplace=True)

In [149]:
cate_data=test_df.select_dtypes(exclude=np.number)
cate_data.head(2)

,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level
0,Male,Suburban,Sedan,Yes,No,Low
1,Male,Urban,SUV,No,No,Low

In [150]:
num_data=test_df.select_dtypes(include=np.number)
num_data.head(2)

,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level
0,61,67725.0,16.9,2,7,4,4.0
1,42,152835.0,41.9,2,9,9,4.0

In [151]:
#encoding test categorical variables
encoded_data=pd.get_dummies(cate_data[['Gender','City_Type','Current_Car_Type']],drop_first=True,dtype=int)

In [152]:
cate_data['Range_Anxiety_Level']=OE.transform(cate_data[['Range_Anxiety_Level']])

In [153]:
cate_data['Home_Charging_Possible']=cate_data['Home_Charging_Possible'].map({'Yes':1,'No':0})
cate_data['Subsidy_Available']=cate_data['Subsidy_Available'].map({'Yes':1,'No':0})

In [154]:
final_encoded_cat_data=pd.concat([cate_data,encoded_data],axis=1)

In [155]:
final_encoded_cat_data.drop(columns=['Gender','City_Type','Current_Car_Type'],inplace=True)

In [156]:
final_encoded_cat_data.head(2)

,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Gender_Male,Gender_Other,City_Type_Suburban,City_Type_Urban,Current_Car_Type_SUV,Current_Car_Type_Sedan,Current_Car_Type_Truck
0,1,0,0.0,1,0,1,0,0,1,0
1,0,0,0.0,1,0,0,1,1,0,0

In [157]:
num_data[['Age','Annual_Income_USD','Daily_Commute_km']]=sc.transform(num_data[['Age','Annual_Income_USD','Daily_Commute_km']])

In [158]:
num_data.head(2)

,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level
0,1.084157,-0.593693,-0.814601,2,7,4,4.0
1,-0.391368,2.376743,0.520636,2,9,9,4.0

In [159]:
final_test_df=pd.concat([final_encoded_cat_data,num_data],axis=1)

In [160]:
model_predictions=lr.predict(final_test_df)

In [161]:
predictions=pd.DataFrame(model_predictions,columns=['Will_Buy_EV'])

In [162]:
predictions.head(3)

   Will_Buy_EV
0            0
1            0
2            0

In [163]:
test=pd.read_csv("/content/test.csv")

In [164]:
predictions['id']=test['id']

In [165]:
predictions.head(2)

   Will_Buy_EV      id
0            0  668665
1            0  668666

In [101]:
#predictions['Will_Buy_EV']=predictions['Will_Buy_EV'].map({1:'Yes',0:'No'})

In [102]:
predictions.head(2)

  Will_Buy_EV      id
0         NaN  668665
1         NaN  668666

In [166]:
predictions.to_csv('EV_predictions2.csv',index=False)